# Generated by Django 4.0.6 on 2022-07-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('fone', models.IntegerField(verbose_name='Fone')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='Atualizado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descricao')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Custo')),
                ('estoque', models.BooleanField(default=True, verbose_name='Estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total')),
                ('cliente', models.ManyToManyField(related_name='clientes', to='core.clientes')),
                ('produto', models.ManyToManyField(related_name='produtos', to='core.produtos')),
            ],
        ),
    ]
